### ISSUE TITLE
A possible feature that loopring should consider to have

### ISSUE THREAD

**Issue by dynabit** [Loopring/protocol#10]
Dear loopring development team,

This might not be very appropriate to be raised as an issue, you may ignore and delete this if you think it is.

So far the project is under development quite well, but the work so far is about ERC20 token exchange, have you ever considered about Ether to be one of the coins that can be included in loopring exchange protocol? Please kindly suggest as the market demands for exchange between Ether and other ERC20 tokens are really out there and take the majority part in daily token trading volume. Hope all go well with loopring development.

Best Regards,
John

**Comment by dong77** [comment]
There is a solution already: check this out - https://weth.io/ we will support WETH trading with other ERC20 tokens. The current plan is to share the same WETH token contract with 0x project.

**Comment by dong77** [comment]
I'm going to close this issue. :)
