### ISSUE TITLE
Use a uint256 to encapsulate various Order/Ring parameters

### ISSUE THREAD

**Issue by dong77** [Loopring/protocol#135]
buyNoMoreThanAmountB, marginSplitPercentage, feeSelectionList can be put into a uint256:

- 1-7 bits: marginSplitPercentage
- 8th bit: buyNoMoreThanAmountB
- 9-15 bits: minimalFillPercentage
- 16th bit: feeSelection

There are more bits available for new features such as those in https://github.com/Loopring/protocol/issues/130

**Comment by Hephyrius** [comment]
I have a few ideas on how this can be implemented, I'm working on it at the moment.

**Comment by dong77** [comment]
Cool,  we need a different branch to merge changes as we are changing the api, need a new major version.


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Harnick Khera <notifications@github.com> Date: 11/19/17  19:45  (GMT-08:00) To: Loopring/protocol <protocol@noreply.github.com> Cc: Daniel Wang <dong77@gmail.com>, Author <author@noreply.github.com> Subject: Re: [Loopring/protocol] optimization: use a uint256 to encapsulate various Order/Ring parameters (#135) 
I have a few ideas on how this can be implemented, I'm working on it at the moment.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Loopring/protocol","title":"Loopring/protocol","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Loopring/protocol"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Hephyrius in #135: I have a few ideas on how this can be implemented, I'm working on it at the moment."}],"action":{"name":"View Issue","url":"https://github.com/Loopring/protocol/issues/135#issuecomment-345583969"}}}

**Comment by Hephyrius** [comment]
I don't have branching permissions, unless I can pull from a fork when I am done? 

I should have something implemented and tested around 4am UTC.

**Comment by dong77** [comment]
I think you can clone the project and create a pull request :)

**Comment by Hephyrius** [comment]
Pull Request at #158, Just needs a few test case fixes. Main .sol code is fine I Think.
