### ISSUE TITLE
Security enhancement for TokenTransferDelegate

### ISSUE THREAD

**Issue by kongliangzhong** [Loopring/protocol#172]
TokenTransferDelegate need to support multisig, or 2 out of 3 confirmations for adding or removing protocol versions.

**Comment by dong77** [comment]
Community contributors, please discuss your solution here before creating a pull request.

**Comment by Brechtpd** [comment]
Seems like something like this should do the trick: [SimpleMultiSig](https://github.com/christianlundkvist/simple-multisig/blob/master/contracts/SimpleMultiSig.sol). There's also an article about this [here](https://medium.com/@ChrisLundkvist/exploring-simpler-ethereum-multisig-contracts-b71020c19037).

**Comment by dong77** [comment]
Will look into it.

**Comment by dong77** [comment]
done
