### ISSUE TITLE
TokenRegistry's unregisterToken need refractory

### ISSUE THREAD

**Issue by dong77** [Loopring/protocol#173]
This `unregisterToken` now takes O(n) time. We really need to change it to O(1) otherwise when the list is too long, we'll eventually run out of gas before a token near the end of the list can be unregistered.

We will probably support thousands of tokens in the future.

**Comment by dong77** [comment]
One idea is to change 
`mapping (address => bool) tokenMap;`
to:
`mapping (address => TokenInfo) tokenMap;`
where TokenInfo is defined as:

```
struct TokenInfo {
    uint index; // index of the address in the array
    uint8 tokenStandard; // 20 or 223
    string symbobl;
}
```
then if a token is removed, we can always move the last token in the list to fill the empy spot in the middle. The order tokens are stored in `tokens` doesn't really matter.

**Comment by Brechtpd** [comment]
See PR #176. I actually did exactly what you proposed. Though I'm not sure if making index == 0 as unregistred is the most logical because index = 0 is valid. Maybe symbol should be used for this if possible?

**Comment by Brechtpd** [comment]
On a side note, does symbol need to be a string? If it's just the ticker of the token it may make more sense to just store a bytes4 or equivalent, should save some gas as well.

**Comment by dong77** [comment]
@Brechtpd the symbol can be 2 to 6 letters and can be even longer.
