### ISSUE TITLE
TokenRegistry should provide a getTokens(skip, size) method.

### ISSUE THREAD

**Issue by dong77** [Loopring/protocol#174]
Another improvement for TokenRegistry is to provide a new method `getTokens(skip, size)` to  enable querying a portion of `tokens` array. If There are 5 thousands tokens, returning the entire list will be very slow  even impossible.

**Comment by Brechtpd** [comment]
Haven't done any testing but something like PR #176 ?
Is getNumTokens() needed? Not sure if reading the length of a large array is an issue. Though I guess you could keep calling getTokens() until you get less tokens than expected.

**Comment by dong77** [comment]
This should be done after a fix for #

**Comment by Brechtpd** [comment]
Alright, I can see how that change will affect this. Thanks, will have a look later.

**Comment by dong77** [comment]
If you would add some more tests to cover the new behavior, I'll increase the reward :)
