### ISSUE TITLE
TokenTransferDelegate can be refactored

### ISSUE THREAD

**Issue by dong77** [Loopring/protocol#175]
I would recommend to use an array to save all the protocol versions in TokenTransferDelegate. The order in which versions are saved in the array doesn't matter, as long as we have a version label in the struct.

`getLatestAuthorizedAddresses` should be unnecessary - we are unlikely to  register more than 100 versions. If we do in the long term, it is possible that we have to improve this TokenTransferDelegate contract as well and deploy a new incompatible version, then we start from clean.

**Comment by Brechtpd** [comment]
Could you explain a bit more what the goal is for this refactoring? Do you want to store all protocol version info in an array, but still have a mapping (e.g. address -> index in the array) to quickly lookup the address info. Or do you want to use only an array, so looking up addresses need a search in the (hopefully small) array.

**Comment by dong77** [comment]
After a second thought, we may need to do much about this contract. I'm closing this issue.
