### ISSUE TITLE
Support a fee discount parameter for each order.

### ISSUE THREAD

**Issue by dong77** [Loopring/protocol#186]
The idea is to enable ring miners to decide if they would like to give an order a fee discount based on certain criteria, for example, the balance of token XYZ in their address. Protocol wont' care why the discount is given, the decision is for the miners off-chain.

**Comment by Hephyrius** [comment]
Would fee discount consist of two elements?
1 - Fee discount (true/false)
2 - Percent discounted

**Comment by dong77** [comment]
to keep the protocol as simple as possible, we decided not to implement this feature.
