### ISSUE TITLE
Wallet get a percentage of mining income.

### ISSUE THREAD

**Issue by dong77** [Loopring/protocol#188]
The current design of Loopring has a nice incentive mechanism for ring-miners. But it doesn't really offer any reward for wallets and website that help user to manage their orders.

We can provide such an incentive mechanism, by allowing wallet to supply an address in the order to split the fee or margin-split with miners. The percentage of LRC or margin-split should be configurable upon deployment.

**Comment by dong77** [comment]
@kongliangzhong  Lets get this done asap. Lets split 25% of the fee to wallet and 75% to ring-minors.. This 25% should be configurable upon deployment.  Lets roll out v1.1.0 in Feb.

**Comment by iswenjie** [comment]
looking forward
