### ISSUE TITLE
Secondary Fee Model

### ISSUE THREAD

**Issue by dong77** [Loopring/protocol#215]
## Motivation
Almost all ICO projects have the desire of 1) adding more value to their issued tokens and 2) creating more demand for their tokens. I propose a Secondary Fee Model that can be added to Loopring Protocol 1.1 or 2.0 to give these projects better reasons to adopt Loopring to trade their tokens.

## Overview
I propose a FeeReimbursePoliciesContract (or FRPC) that allows an ICO project (who issued token XYZ) to create one or more policies — the address that used to create a policy is called the policer owner. 

Here are some details about a policy:
- it locks `X` LRC up to` N` blocks.
- it can specify that if an address is to buy token XYZ of amount `B`, AND if the miner decided to take LRC as fee, then the corresponding policy owner will pay `my%` (`m` > 1) LRC for the trading address until the deposited LRC is exhausted. As a result, the trading address only has to pay `1-y%` LRC as fee. FRPC will provide a way of specifying how `y` is calculated based on `B`. This policy encourages people to buy XYZ token with less LRC fee.
- It can also specify that if an address is to do any token trading, as long as the address hold `H ` amount of XYZ , AND if the miner decided to take LRC as fee, then the corresponding policy owner will pay `mz%` (`m` > 1) LRC for the trading address until the deposited LRC is exhausted, and the trading address only pays `1-z%` LRC as fee. There will be a way of specifying how `z` is calculated based on `H`. This policy encourage people to hold XYZ token.
- It should allow last two rules co-exist.

Note that a policy owner needs to pay `my%` or `mz%` LRC to the ring miner instead of `y%` or `z%`. This is because applying policies will consume more gas so the extra LRC will be required to compensate this additional cost. The multiplier m should also be configurable by policy owners.

Loopring ring-miners will decide if and what policies to apply for  a ring,  as for any single token, there may be multiple policies available. Miner only takes the best ones for the most profit.

From the user’s perspective, holding XYZ token or buying XYZ token eliminate part or even all the LRC trading fee.

**Comment by munair** [comment]
You would be losing elegancy by implementing this FRPC.

**Comment by dong77** [comment]
That’s exactly the reason we didn’t start implementing this feature.
