### ISSUE TITLE
ERC20Token constructor should check input parameters

### ISSUE THREAD

**Issue by dong77** [Loopring/protocol#281]
It should check:
1) token symbol contains only uppercase A to Z and ".".  "." can occur at most once in the middle. The token symbol shall be less than 10 chars.
2) token name contains only "A-Za-z_-" and " ". Lengh <= 128 chars.
3) digits shall be >=3 and <= 8

**Comment by Orangem21** [comment]
maybe also shouldn't use the same symbol like LRC or anything else which was in registered token map already.

**Comment by Orangem21** [comment]
```
mapping(string => bool) token_symbols;
...
require(!token_symbols[symbol]);
```

**Comment by dong77** [comment]
Using existing name will make the registration fail thus the mint of the new token fail as well.

**Comment by Orangem21** [comment]
OK, I find the ``` symbolMap[]```

**Comment by JacksonTom** [comment]
留个中文

**Comment by dong77** [comment]
fixed
