### ISSUE TITLE
Potential bug: RingMined emitting the same ring hash across multiple orders.

### ISSUE THREAD

**Issue by Hephyrius** [Loopring/protocol#312]
While i was working on a prototype. I was looking at the events emitted by the current [deployed](https://etherscan.io/address/0x4019440BBe5882915db9F2cAe972a518DB346C62#events) contract and I noticed that orders are outputting the same ringhash across different orders. 

For example transactions [0x9c8922bc0a4006a57ecf7de10ceb29af13d112180747a290234cc5bd57b197e4](https://etherscan.io/tx/0x9c8922bc0a4006a57ecf7de10ceb29af13d112180747a290234cc5bd57b197e4) and [0x7dae0f38074df421e7ad250c7ab26f8d4ffc5872a0f0ae1323846b8c5f57af95](https://etherscan.io/tx/0x7dae0f38074df421e7ad250c7ab26f8d4ffc5872a0f0ae1323846b8c5f57af95). The same ringhash has in fact been used for all submitRing instances to the contract.

I'm submitting this as an issue as I am not sure if the recent restructuring and changes address this fully.

**Comment by dong77** [comment]
Two rings may have the same hash if 1) all mining parameters are the same, and 2) all orders are the same and in the same order. @kongliangzhong I am pretty sure about this, but I want you to confirm it.

**Comment by dong77** [comment]
BTW, @Hephyrius the URLs you used are for old versions. For the latest please see : https://etherscan.io/address/0xb1170dE31c7f72aB62535862C97F5209E356991b#events

**Comment by Hephyrius** [comment]
The name lead me to assume that each ring would have a unique hash, this might be a misunderstanding on my part. Although, The ringIndex would be a unique enough feature for specifically searching for a ring I guess. 

For now I'll be using the 1.4 version purely based on the fact the protocol is rapidly changing at the moment, making it hard to keep track of whats going on at times.

This is just a trailing thought, would there actually be any merit to emitting the ring hash at all? Ring miners could look up all of there mined rings purely based on ring index or by looking up all rings that emitted the miners address. this would save between ~400-700 gas too,

**Comment by dong77** [comment]
I like what you proposed, maybe we can indeed remove ringhash from the event.

**Comment by kongliangzhong** [comment]
The ring hash identified a ring and a ring can be settled several times if balances or approved amount of orders changed.

**Comment by dong77** [comment]
I'm closing this issue.
