### ISSUE TITLE
Tests Not working

### ISSUE THREAD

**Issue by akash2504** [Loopring/protocol#322]
While i was making some gas optimizations, realized that the latest code doesnt have all the test cases working. Is there some other branch i should work on?

**Comment by Hephyrius** [comment]
The protocol is undergoing some major changes at the moment ( see #316 ), I think @kongliangzhong is currently working on fixing the tests to work with the new changes.

**Comment by kongliangzhong** [comment]
try `npm install` and retry, please. All tests passed on my computer.

**Comment by dong77** [comment]
fixed
