### ISSUE TITLE
Optimization: batch update cancelledOrFilled amount

### ISSUE THREAD

**Issue by dong77** [Loopring/protocol#323]
Inside the loop in the `settleRing` method,  this function is called multiple times, 
```
     // Update fill records
            if (state.buyNoMoreThanAmountB) {
                delegate.addCancelledOrFilled(state.orderHash, nextFillAmountS);
            } else {
                delegate.addCancelledOrFilled(state.orderHash, state.fillAmountS);
            }
```

We can construct an array first then pass it to `batchTransferToken` (probably rename it to `batchTransferTokenAndUpdateTradeHistory`.

**Comment by Brechtpd** [comment]
That's something I did in #309

**Comment by dong77** [comment]
Oh, will take a look.  We credit it to you if the changes are similar.

**Comment by dong77** [comment]
fixed
