### ISSUE TITLE
force marginSplit to 100 when lrcFee is 0

### ISSUE THREAD

**Issue by jonasshen** [Loopring/protocol#70]
After reviewing of the protocol code, I found that marginSplit can be less then 100 when lrcFee was 0. Is this a bug or designed?

**Comment by dong77** [comment]
I believe this is a bug.

**Comment by jonasshen** [comment]
how we fix it then? Reject the order or force the marginSplit to 100? This may add gas after the fix.

**Comment by kongliangzhong** [comment]
I have fix this. see commit b65f0adaada9686fd46f95a5d4247cddf402dc05
